filter:
    excluded_paths:
        - 'bin/*'
        - 'vendor/*'
build:
    tests:
        override:
            -
                command: bin/phpunit
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
    environment:
        php:
            version: 7.1
            ini:
                'date.timezone': 'Europe/Berlin'

tools:
    external_code_coverage: true

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2

    php_cs_fixer:
        enabled: true
        config:
          level: psr2

    php_hhvm:
        enabled: true

    php_mess_detector:
        enabled: true

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true
